pollution <- read.table(file = "avgpm25.csv", header = T, sep=",")
attach(pollution)
names(pollution)
summary(pollution)
head(pollution, 5)
summary(pollution, 5)
summary(5, pollution)
fivenum(pollution)
str(pollution)
summary(pollution)
str(pollution)
